spring:
  application:
    name: microservice-users
  datasource:
    url: ${db_uri:jdbc:mysql://localhost:3306/springboot_cloud_aws}
    username: ${db_user:root}
    password: ${db_pass:}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
server:
  port: ${port:8092}

eureka:
  client:
    service-url:
      defaultZone: ${eureka_uri:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true


management:
  tracing:
    sampling:
      probability: 1.0
    export:
      zipkin:
        endpoint: ${zipkin_server_uri:http://localhost:9411/api/v2/spans}
