info:
  name: config-server
  type: http
  seq: 3

http:
  method: GET
  url: http://localhost:8888/microservice-item/dev
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
